---
title: "Notes"
author: "Juan Rocha"
output: html_document
---


## Steps to recompile website:

1. Build again the map from raw data: This creates target file names, and target links on the map explorer.
    - 260827: 31 cases with missing coords
2. Re-build references for missing cases: 99-refs.R
    - 10 cases with no reference at all: 
[1] "1621" "524"  "527"  "530"  "335"  "525"  "526"  "531" 
 [9] "3736" "3588"
3. Re-run 99-images to correct links [not necessary, only once I think]
4. 


**260827**

Hack response. Two days ago the original website was hacked, so I'm moving this one into production. Here are the steps of what was done to improve the current draft:

- We have new case studies, and some errors were corrected from the old ones (e.g. coordianates). So all CS need to be recompiled. Old CS deteled (all files starting on "cs"). Script: 99-file_mngt.R
- 31 case studies missing coordinates

**260825**

- Modify the rs_template? or do by hand as I review?
- Updated coral transitions: created a carousel with pictures, changed the analysis section to include tabs so the scrolling is not too long. All references updated.
- Idea: add a tab on "key statistics" where you show the countries most affected and the time line
- Currently the drivers summary table is lost, and the ES per stakeholders originally missing. Uncertainty assessment and leverage points are also missing from the original draft.
- Perhaps add table with case studies?
- Carousel for pictures: add a sub-caption with credits

**260625**

- New batch of cases updated to the map (not yet pages) N = 3722
- There are errors on coordinates and non-informative names
- There are errors on unpublished generic RS
- Solve a system for referencing
- Fix pictures carrousel

**241115**

- Think of online explorer types
- RA description: what can she/he do, time and cost or postdoc.
    - Things that need fixing: text of CS RS analysis
    - whish list of add ons
    

**240803**
- Netifly manual test working
- ~~Re-create map with new url~~
- ~~Upload all RS and CS~~
- ~~colour case maps on RS pages by evidence type~~
- Add better formatting for references and create bibtex block automatically
- ~~Advance search for both RS and CS~~
- ~~Funding acknowledgement~~
- Publish drylands degradation (JCR), disease outbreaks (JCR), invasive species
In review:
    - Garry: forest croplands, dams
    - Oonsie: soil structure (primary productivity)
Future to add:
    - Traffic jams
    - Pollination collapse
    - Fire regime
    - Soil productivity
    - Community and population shifts (terrestrial) [multiple cases: wolfs, rewilding]
    - Freshwater salinization
    - River delta accretion to recession [cases Mississippi]
    - Glaciers accretion to recession
    - Forest die-offs
    - Dryland degradation

**240729**
- CLDs functions created: perhaps add legend and caption to figure
- update the RS template to include CLD and RS analysis
- clean up github
- figure out how to cache, how to avoid rendering non-changed files (check workflow)

**240726**
- Generic regime shifts files created: the RS analysis and CLDs need to be added manually, it does not exist as downloadable files from RSDB.
- Map not working, notice that for RS where there is no CS, the map is empty
- RS: create a map that highlight the biomes where it can occur, and showcases the case studies where it has already occurred, coloured by evidence type, or a time line, or something like that.
- I webscrapped the RSDB to recover the RS analysis text for both regime shifts and detailed case studies. Not all have the same level of detail, many miss the table summaries for drivers and impacts on ES. 

**231008**:
- The skeleton of the website is up and running. Created with script 00 and then filled content manually for front end pages
- A script that takes the current database of case studies has been created 99-case_studies.R that automatically creates Rmd documents, one per case study with the right content and formatting. One could do kniting rmarkdown with parameters, but it will only create the html variants, not the raw Rmd. I need the raw Rmd so in the future it's easy to update each as new literature is published. 

TODOs:

~~1. Do the same for generic regime shifts~~
2. Update interactive maps with links to the case studies.
~~3. Implement a routine to bring pictures automatically, without importing files. If all pics are CC, they should be available with a link from the internet. So no need to have the original files on the folder. If necessary later you can download, but key to have the links and pics immersed in the text.~~
~~4. Use the CLDs raw data to create interactive networks.~~


