---
title: "Case studies"
---

There are two types of case studies: basic case study provides a reference and a few categorical variables that summarizes a case; detailed case study offers additional narrative information about what happened. The latter follow a similar structure to generic regime shifts and are often reviewed by an expert on the case.


```{r map, echo = FALSE, message=FALSE, warning=FALSE, fig.cap="The map offers links to literature reviews for generic regime shifts (in the legend) and links to over 3000 case studies (dots on the map). Each link will take you to a page where you can learn more about how the regime shift works.", out.width="100%", out.height="650px"}
library(tidyverse, quietly = TRUE)
library(htmltools)
library(widgetframe)

load("assets/map_rsdb.Rda")
frameWidget(map_rsdb, width = "100%", height = "650")
```

### Summary


### Advanced search

```{r tabel, warning=FALSE, message=FALSE, echo = FALSE, out.width="100%"}
library(DT)

#options(DT.options = list(pageLength = 50))
load("assets/cases_db.Rda")

dat |> #names() |> 
    mutate(popups = str_remove_all(popups, "<b>|</b>")) |> 
    select(
        `Case study` = popups,
        `Regime Shift` = link_rs, 
        Year = year_or_duration,
        `Drivers` = key_direct_drivers, 
        `Ecosystem type` = ecosystem_type,
        Country = location_countries,
        Evidence = sources_of_evidence
        
    ) |>
    datatable(escape = c(1), filter = "top")
```


